// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usersWire

import (
	"Project/internal/DB"
	"Project/internal/respository"
	"Project/internal/respository/cache"
	"Project/internal/respository/dao"
	"Project/internal/service"
	"Project/internal/web"
)

// Injectors from wire.go:

func InitWebService() *web.UserHandle {
	db := DB.InitDB()
	userDataAccess := dao.NewUserDao(db)
	cmdable := DB.InitRedis()
	userRedisCache := cache.NewUserCache(cmdable)
	userStorage := respository.NewUserRepo(userDataAccess, userRedisCache)
	userServiceImpl := service.NewUserService(userStorage)
	codeRedisCache := cache.NewCodeCache(cmdable)
	codeStorage := respository.NewCodeRepo(codeRedisCache)
	shortMessageService := InitFakerSMS()
	codeServiceImpl := service.NewCodeService(codeStorage, shortMessageService)
	userHandle := web.NewUserHandle(userServiceImpl, codeServiceImpl)
	return userHandle
}
