// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usersWire

import (
	"Project/webBook_git/internal/DB"
	"Project/webBook_git/internal/respository"
	"Project/webBook_git/internal/respository/cache"
	"Project/webBook_git/internal/respository/dao"
	"Project/webBook_git/internal/service"
	"Project/webBook_git/internal/web"
)

// Injectors from wire.go:

func InitWebService() *web.UserHandle {
	db := DB.InitDB()
	userDao := dao.NewUserDao(db)
	cmdable := DB.InitRedis()
	userCache := cache.NewUserCache(cmdable)
	userRepo := respository.NewUserRepo(userDao, userCache)
	userService := service.NewUserService(userRepo)
	userHandle := web.NewUserHandle(userService)
	return userHandle
}
