services:
  db:
    image: mysql:8.2.0
    restart: always
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: webook
    ports:
#      - 将容器的3306端口映射到宿主机的13306端口
      - "13306:3306"
    volumes:
#      - ./data:/var/lib/mysql
#      - 持久化卷，将宿主机的./data目录挂载到容器的/var/lib/mysql目录
      - ./data/dao:/var/lib/mysql
      - ./script/mysql/:/docker-entrypoint-initdb.d/
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6479:6379"
